name: Seasonal Workflow Activator

on:
  schedule:
    # Run monthly on the 1st at 00:01 UTC
    - cron: '1 0 1 * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-seasonal-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - name: Create seasonal workflow manager script
        run: |
          cat > manage-seasonal-workflows.js << 'EOF'
          /**
           * Simple script to manage sport workflow files based on season
           */
          const fs = require('fs');
          const path = require('path');
          
          // Define sports seasons (months are 1-indexed)
          const sportSeasons = {
            nba: { start: 10, end: 6 },  // October to June
            mlb: { start: 4, end: 10 },  // April to October
            nhl: { start: 10, end: 6 }   // October to June
          };
          
          // Get current month
          const currentMonth = new Date().getMonth() + 1; // JS months are 0-indexed
          
          // Check which sports are in season
          const inSeasonSports = [];
          const outOfSeasonSports = [];
          
          Object.entries(sportSeasons).forEach(([sport, season]) => {
            if (season.start <= season.end) {
              // Normal season (e.g., April to October)
              if (currentMonth >= season.start && currentMonth <= season.end) {
                inSeasonSports.push(sport);
              } else {
                outOfSeasonSports.push(sport);
              }
            } else {
              // Season crosses year boundary (e.g., October to June)
              if (currentMonth >= season.start || currentMonth <= season.end) {
                inSeasonSports.push(sport);
              } else {
                outOfSeasonSports.push(sport);
              }
            }
          });
          
          console.log('In-season sports:', inSeasonSports);
          console.log('Out-of-season sports:', outOfSeasonSports);
          
          // Workflow files directory
          const workflowsDir = path.join('.github', 'workflows');
          
          // Activate/deactivate workflows based on season
          inSeasonSports.forEach(sport => {
            const workflowFile = path.join(workflowsDir, `${sport}-edge-detection.yml`);
            const workflowDisabledFile = path.join(workflowsDir, `${sport}-edge-detection.yml.disabled`);
            
            // If workflow is disabled, enable it
            if (fs.existsSync(workflowDisabledFile)) {
              fs.renameSync(workflowDisabledFile, workflowFile);
              console.log(`Activated ${sport} workflow for the season`);
            } else if (fs.existsSync(workflowFile)) {
              console.log(`${sport} workflow is already active`);
            } else {
              console.log(`Warning: No workflow file found for ${sport}`);
            }
          });
          
          outOfSeasonSports.forEach(sport => {
            const workflowFile = path.join(workflowsDir, `${sport}-edge-detection.yml`);
            const workflowDisabledFile = path.join(workflowsDir, `${sport}-edge-detection.yml.disabled`);
            
            // If workflow is enabled, disable it
            if (fs.existsSync(workflowFile)) {
              fs.renameSync(workflowFile, workflowDisabledFile);
              console.log(`Deactivated ${sport} workflow for the off-season`);
            } else if (fs.existsSync(workflowDisabledFile)) {
              console.log(`${sport} workflow is already inactive`);
            } else {
              console.log(`Warning: No workflow file found for ${sport}`);
            }
          });
          EOF
      
      - name: Execute seasonal workflow manager
        run: node manage-seasonal-workflows.js
      
      - name: Commit and push workflow changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/workflows/
          git commit -m "Update seasonal workflow activation status [automated]" || echo "No changes to commit"
          git push