name: Build and Deploy NBA Betting Analysis

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9 AM UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Create site directory
        run: |
          mkdir -p site/reports

      - name: Run NBA betting analysis
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          node index.js

      - name: Copy reports to site directory
        run: |
          cp -R reports/* site/reports/

      - name: Create index page
        run: |
          node -e '
            const fs = require("fs");
            const path = require("path");

            // Function to create index.html
            function createIndexHtml() {
              const reportsDir = "./reports";
              const dates = fs.readdirSync(reportsDir).filter(file =>
                fs.statSync(path.join(reportsDir, file)).isDirectory()
              );

              // Sort dates in descending order (newest first)
              dates.sort((a, b) => b.localeCompare(a));

              let html = `
                <!DOCTYPE html>
                <html>
                <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>NBA Betting Analysis Reports</title>
                  <style>
                    body {
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                      line-height: 1.6;
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                      color: #333;
                    }
                    h1, h2, h3 {
                      color: #222;
                    }
                    a {
                      color: #0366d6;
                      text-decoration: none;
                    }
                    a:hover {
                      text-decoration: underline;
                    }
                    .date-section {
                      margin-bottom: 30px;
                      border-bottom: 1px solid #eee;
                      padding-bottom: 20px;
                    }
                    .report-list {
                      list-style-type: none;
                      padding-left: 20px;
                    }
                    .report-list li {
                      margin-bottom: 10px;
                    }
                  </style>
                </head>
                <body>
                  <h1>NBA Betting Analysis Reports</h1>
                  <p>Daily betting analysis and recommendations generated with Claude 3.7 Sonnet.</p>
              `;

              dates.forEach(date => {
                const dateDir = path.join(reportsDir, date);
                const files = fs.readdirSync(dateDir);

                // Group files by type
                const analysis = files.filter(f => f.includes("nba_edge_analysis"));
                const mdRecommendations = files.filter(f => f.includes("recommended_bets") && f.endsWith(".md"));
                const htmlRecommendations = files.filter(f => f.includes("recommended_bets") && f.endsWith(".html"));

                if (analysis.length > 0 || mdRecommendations.length > 0 || htmlRecommendations.length > 0) {
                  html += `
                    <div class="date-section">
                      <h2>${formatDate(date)}</h2>
                      <ul class="report-list">
                  `;

                  // Add HTML recommendations first
                  htmlRecommendations.forEach(file => {
                    html += `
                      <li>
                        <a href="reports/${date}/${file}">Betting Recommendations (HTML)</a>
                      </li>
                    `;
                  });

                  // Add markdown recommendations
                  mdRecommendations.forEach(file => {
                    html += `
                      <li>
                        <a href="reports/${date}/${file}">Betting Recommendations (Markdown)</a>
                      </li>
                    `;
                  });

                  // Add full analysis
                  analysis.forEach(file => {
                    html += `
                      <li>
                        <a href="reports/${date}/${file}">Full Analysis</a>
                      </li>
                    `;
                  });

                  html += `
                      </ul>
                    </div>
                  `;
                }
              });

              html += `
                  <footer>
                    <p>Generated using NBA Edge Detection System with Claude Extended Thinking</p>
                  </footer>
                </body>
                </html>
              `;

              fs.writeFileSync("./site/index.html", html);
              console.log("Created index.html");
            }

            // Helper function to format date
            function formatDate(dateStr) {
              const date = new Date(dateStr);
              return date.toLocaleDateString("en-US", {
                weekday: "long",
                year: "numeric",
                month: "long",
                day: "numeric"
              });
            }

            // Create the index.html file
            createIndexHtml();
          '

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
